### ISSUE TITLE
Error: EACCES: permission denied, open '/etc/ssh/ssh_config'

### ISSUE THREAD

**Issue by ddrager** [deployphp/action#1]
Hello, 

When not using known_hosts secret, action attempts to add this onto the ssh_config file:

```fs.appendFileSync(`/etc/ssh/ssh_config`, `StrictHostKeyChecking no`)```

However this makes the action fail with the error: 

`Error: EACCES: permission denied, open '/etc/ssh/ssh_config'`

When adding known keys to the action, this does not run so does not error out.

**Comment by antonmedv** [comment]
Can you make PR to fix it?
