### ISSUE TITLE
Exit code on error

### ISSUE THREAD

**Issue by giraz82** [deployphp/action#13]
It seems that if an error occurs during deploy process, the action completes successfully. In such way there is no evidence that the deploy failed, unless to check carefully the action log.

```
...
...
➤ Executing task deploy:update_code
➤ Executing task deploy:failed
• done on [xxx.xxx.xxx.xxx]
✔ Ok [0ms]
```
![image](https://user-images.githubusercontent.com/5285724/117221431-88eb6900-ae09-11eb-862c-f693e6bb3496.png)

Am I missing something?
Thank you

**Comment by mmenozzi** [comment]
I have the same issue.
