### ISSUE TITLE
Error ssh  Permission denied (publickey,password). failed

### ISSUE THREAD

**Issue by etokas** [deployphp/action#30]
Hello !
When i want to deploy i 'have this error

`Run deployphp/action@v1
Using "deployer.phar".
[localhost] > git rev-parse --abbrev-ref HEAD
[localhost] < ci
✈︎ Deploying tag develop on preprod
• done on [preprod]
➤ Executing task deploy:prepare
[preprod] > echo $0
[preprod] < Warning: Permanently added 'host,ip' (ECDSA) to the list of known hosts.
[preprod] < Permission denied, please try again.
[preprod] < Permission denied, please try again.
[preprod] < user@host: Permission denied (publickey,password).
➤ Executing task deploy:failed
• done on [preprod]
✔ Ok [1ms]
➤ Executing task deploy:unlock
[preprod] > rm -f /var/www/app/.dep/deploy.lock
[preprod] < Permission denied, please try again.
[preprod] < Permission denied, please try again.
[preprod] <  user@host: Permission denied (publickey,password).

In Client.php line 103:

  [Deployer\Exception\RuntimeException (-1)]                          
  The command "rm -f /var/www/app/.dep/deploy.lock" failed.  

  Exit Code: -1 (Unknown error)                                       

  Host Name: preprod                                                  

  ================                                                    
  Permission denied, please try again.                                
  Permission denied, please try again.                                
  user@host: Permission denied (publickey,password).`

my conf
`name: Deploy staging

on:
  push:
    branches:
      - ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'

      - name: Deploy on staging
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy preprod --tag=develop -vvv
`
I used deployer 6.8.0

can you help me please ?

**Comment by antonmedv** [comment]
Please use discussions.
