### ISSUE TITLE
github actions report error

### ISSUE THREAD

**Issue by tlerbao** [deployphp/action#44]
Thanks for open source. May I ask what is the reason for this?
<img width="791" alt="image" src="https://user-images.githubusercontent.com/20442232/188272144-9840d775-6c50-45a9-a7b6-5277341bcffb.png">

**Comment by antonmedv** [comment]
Check what you can clone on server (without agent forwarding)

**Comment by tlerbao** [comment]
I connected to the server to test and found that it was because the first clone project, the github ip was not added to the know-host, how to solve this problem?

Does each server manually clone the project once, and then use actions to deploy after adding know-host?

or another way
