### ISSUE TITLE
Downloaded `deployer.phar` should be the latest version

### ISSUE THREAD

**Issue by benjaminmal** [deployphp/action#45]
I have this error when running my deployment workflow:

![Capture d’écran 2022-09-08 à 14 36 41](https://user-images.githubusercontent.com/58468686/189124021-93cee392-d19f-47dd-8b4c-3fc2498019ad.png)

It turns out the version downloaded via https://deployer.org/deployer.phar is 6.8.0. I think the action should download the latest version available by default, or maybe a required parameter should be added to select the major version of the downloaded `deployer.phar`. Linked to https://github.com/deployphp/deployer/issues/3225.

**Comment by TTATPuOT** [comment]
Same error. Thanks a lot @benjaminmal for working solution.

I also add
```
tools: composer:v2
```
to `shivammathur/setup-php@v2` for composer installs.

**Comment by antonmedv** [comment]
Lets do it this way: if I gonna get donation in amount of $100, I'll work on create a link which points to latest dep phar.

**Comment by benjaminmal** [comment]
@antonmedv Kind of expensive link :P I can suggest adding a `latest` version in [manifest.json](https://deployer.org/manifest.json) and setting in the action `latest` as default value for `deployer-version`. It should work automatically in the action.

```json
[
    ...
 
    {
        "name": "deployer.phar",
        "sha1": "bf46ca3ff7339d644220e949c2c71994749cf561",
        "url": "https:\/\/github.com\/deployphp\/deployer\/releases\/download\/v7.0.2\/deployer.phar",
        "version": "7.0.2"
    },
    {
        "name": "deployer.phar",
        "sha1": "bf46ca3ff7339d644220e949c2c71994749cf561",
        "url": "https:\/\/github.com\/deployphp\/deployer\/releases\/download\/v7.0.2\/deployer.phar",
        "version": "latest"
    }
]
```

**Comment by antonmedv** [comment]
Should be fixed.
