### ISSUE TITLE
Node12 is deprecated

### ISSUE THREAD

**Issue by asychev** [deployphp/action#50]
Node 12 has been out of support since [April 2022](https://github.com/nodejs/Release/#end-of-life-releases), as a result Github have [started](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) the deprecation process of Node 12 for GitHub Actions.

This action needs to be updated.

**Comment by asychev** [comment]
@devenes Thanks, much appreciated. Can we also cut a new release?

**Comment by devenes** [comment]
> @devenes Thanks, much appreciated. Can we also cut a new release?

I agree with you, a new release would be a great and quick solution for pipeline workflows broken by GitHub Actions warnings.

**Comment by antonmedv** [comment]
Fixed

**Comment by fpalamour** [comment]
Which release are we supposed to use ? The v1 tag still points to v1.0.12 and v1.0.17 uses node 12.

**Comment by devenes** [comment]
You are right @fpalamour! 👀 

This points the latest tag but it is very old:

> v1.0.12 antonmedv released this Oct 16, 2021. 

@antonmedv Can we check it to use the latest config?

**Comment by cmorbitzer** [comment]
Looks like we're pointing at 1.0.22 now 👍  Thanks! @antonmedv
