### ISSUE TITLE
Egress is over the account limit

### ISSUE THREAD

**Issue by asychev** [deployphp/action#51]
Sometimes action fails with this error message:

Run deployphp/action@v1
Downloading "https://github.com/deployphp/deployer/releases/download/v7.0.2/deployer.phar".
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>ServerBusy</Code><Message>Egress is over the account limit.
RequestId:db600160-501e-0064-3a16-dfd3fd000000
Time:2022-10-13T15:14:51.1843133Z</Message></Error>

**Comment by antonmedv** [comment]
Azure issues not related to  Deployer.
