### ISSUE TITLE
Task composer install and npm build in runner

### ISSUE THREAD

**Issue by n-ramos** [deployphp/action#54]
Hello,

I would like to know if it's possible to.build assets and vendor only on ci and not directly on Host ?

**Comment by antonmedv** [comment]
Will update docs.

**Comment by n-ramos** [comment]
> Will update docs.

Hello, in this repository ? :)

**Comment by antonmedv** [comment]
On website.

**Comment by n-ramos** [comment]
> On website.

Thanks,
Can you give me a link to the documentation for this feature please?

**Comment by antonmedv** [comment]
I still didn’t find the time to do it. Probably in some future. 

Donations are good motivation to for on a specific project. ;)

**Comment by n-ramos** [comment]
> I still didn’t find the time to do it. Probably in some future.
> 
> Donations are good motivation to for on a specific project. ;)

Ohw ok, can u explain me how to do it maybe ? 

I can create a PR after and donate if u want, i just really need to know how can i do that =)

Thanks by advance

**Comment by antonmedv** [comment]
> Ohw ok, can u explain me how to do it maybe ?

Well, use custom tasks =))
