### ISSUE TITLE
PHP Warning:  require(contrib/npm.php): Failed to open stream: No such file or directory in

### ISSUE THREAD

**Issue by Edvinaz** [deployphp/action#55]
Hello,

I've stuck with deployer, maybe I do something wrong... 
I have configured deploy.php in my project and tryed to create github action to automatically deploy, but getting error `PHP Warning:  require(contrib/npm.php): Failed to open stream: No such file or directory in /home/runner/work`
Tryes to use Github Actions example from your site.

**Comment by antonmedv** [comment]
Please open a discussion instead.
