### ISSUE TITLE
Deployer 7.3.1 is missing in the manifest

### ISSUE THREAD

**Issue by Seb33300** [deployphp/action#71]
[Deployer 7.3.1](https://github.com/deployphp/deployer/releases/tag/v7.3.1) is missing in the manifest file when using the `deployer-version` option:
https://deployer.org/manifest.json

Also, this error is not triggered: https://github.com/deployphp/action/blob/06aeb295d6432970d615c5551e3d941e50349c46/index.js#L97-L99
You probably need to check for 'undefined' as well (not only null)

Here is the result:
```
    ...
    {
        "name": "deployer.phar",
        "sha1": "7fc18128545bebaa13fc7f3daa79b3e1fa67fd1e",
        "url": "https:\/\/github.com\/deployphp\/deployer\/releases\/download\/v7.3.0\/deployer.phar",
        "version": "7.3.0"
    }
]

100 29938  100 29938    0     0  32587      0 --:--:-- --:--:-- --:--:-- 32576
$ curl -LO undefined
curl: Remote file name has no length!
curl: (23) Failed writing received data to disk/application
Downloading "undefined".
Error: curl: Remote file name has no length!
```

**Comment by Seb33300** [comment]
issue about undefined is duplicated to https://github.com/deployphp/action/issues/63

**Comment by SimJoSt** [comment]
Yes, it is related, but the other issue only tries to fix the problem with the action failing because the current version is not present in the manifest.
To use the action with the newest version, the manifest should still be updated to contain the most current version.
