### ISSUE TITLE
GitHub Actions' native `run`

### ISSUE THREAD

**Issue by michael-bullimore-uk** [deployphp/action#75]
Hi peeps.!

Many thanks to you all for making and maintaining Deployer. ♥️🙂

Just a quick question here. Is it possible to just use GitHub Actions' native `run` to run Deployer as opposed to using this action?

I'm trying to understand the purpose of this action vs the above, as assuming I have dealt with SSH authentication in my workflow, does this action offer any benefits?

Ta

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/action/issues/75">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/action/issues/75/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/action/issues/75/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Yes, it is totally fine to just use `run:`.  ;)
