### ISSUE TITLE
Node.js 16 actions are deprecated -> use Node.js 20 instead

### ISSUE THREAD

**Issue by Arachnos** [deployphp/action#78]
Hi everyone !

When running Deployer action on GitHub Workflow, we have this message : 
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: deployphp/action@v1.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

Is it planned to upgrade the version of Node to 20 ?

**Comment by madurapa** [comment]
`uses: actions/checkout@main` instead of `uses: deployphp/action@v1` until this PR been released.
