### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by iantearle** [deployphp/action#8]
What is it that this action actually does? What's the end result? Are any normal steps to deploying affected, or does this deploy when Git receives a push? 

I may just be suffering from not enough coffee on a Monday morning, but I'm struggling to see in the code what's going to happen...

**Comment by antonmedv** [comment]
It’s pretty simple. Just dep deploy. From my prospective it hard to tell what to improve in docs. Maybe you can add pr with your view of better doc?

**Comment by zivan** [comment]
I tryed to use examples but they did not work
Look, https://github.com/nsolv/demodeployphp

1. I created simple deploy.php and it worked when I ran it localy.
2.I added simple action by example (https://github.com/deployphp/action#example), but I had error
Run deployphp / action @ master
   with:
     private-key: ***
     dep: deploy -vvv
Error: Command failed with ENOENT: deployer.phar deploy -vvv
spawn deployer.phar ENOENT

3.I created fork https://github.com/zivan/action and fixed two problems. First, you have to use relative path when execute command. Second, files .ssh / known_hosts and .ssh / config must have permissions 600, if it is not true you will have a error from ssh client.

But I had a error when git clone repository.

4. When using github action have to set git_tty false into deploy.php. I think should write about git_tty into docs, It can help to safe nervous.

Now, everything works fine.

**Comment by antonmedv** [comment]
A PR?
