### ISSUE TITLE
Upgrade Node.js to version 20

### ISSUE THREAD

**Issue by Seb33300** [deployphp/action#80]
Our workflow is triggering this warning:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: deployphp/action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by nilsandresen** [comment]
It's already fixed in [373ff33](https://github.com/deployphp/action/pull/79) Just not released yet. You could use it like mentioned in the comment for now:
uses: deployphp/action@master instead of deployphp/action@v1

**Comment by madurapa** [comment]
Please release the fix.

**Comment by DannyvdSluijs** [comment]
This actually was done 5 days ago, see https://github.com/deployphp/action/releases
