### ISSUE TITLE
Curl error

### ISSUE THREAD

**Issue by yun548** [deployphp/action#81]
Getting this error today : `curl: (28) Failed to connect to deployer.org port 443 after 135428 ms: Connection timed out`

Deployer version 6.9 using deployphp/action@master

The url replies with a 200 in a timely manner when I curl from the CLI.

Maybe it would make more sense to node http module to retrieve to contents of the manifest ?

**Comment by minayaleon** [comment]
I've same problems

**Comment by antonmedv** [comment]
Duplicate of https://github.com/deployphp/deployer/discussions/3824
