### ISSUE TITLE
Change download of binary

### ISSUE THREAD

**Issue by ntzrbtr** [deployphp/action#90]
As the manifest.json file will likely be removed (see https://github.com/deployphp/deployer/issues/3814), the download of the deployer binary should be changed: in the manifest.json file the latest version is 7.4.1, so when using a later version (e.g. the latest, which is 7.5.4), the Github workflow fails.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/action/issues/90">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/action/issues/90/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/action/issues/90/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
Looks like a lot of people dependent on manifest.json file. So I decided to keep the file. I will write a cron job to update manifest.json daily.
