### ISSUE TITLE
The version "7.5.4"" does not exist in manifest.json

### ISSUE THREAD

**Issue by Schrolli91** [deployphp/action#91]
After the update to 7.5.4 i will get the following error in the action run:

```
::error::The version "7.5.4"" does not exist in the "https://deployer.org/manifest.json" file."
$ sudo chmod +x deployer.phar
chmod: cannot access 'deployer.phar': No such file or directory
::error::chmod: cannot access 'deployer.phar': No such file or directory%0A    
at dep (file:///run/act/actions/deployphp-action@v1/index.js:104:12)%0A    exit code: 1
```

In the manifest file I cant find this version - How can I fix this problem?

**Comment by antonmedv** [comment]
We need to write a script which updates manifest file from guitar releases

**Comment by Schrolli91** [comment]
Is there any option of an hotfix? Currently there are no automated deployments possible via actions.

**Comment by antonmedv** [comment]
You can install deployer via composer in action.

**Comment by nvahalik** [comment]
@antonmedv Is there a way we can support you in this?

**Comment by antonmedv** [comment]
Sure! https://github.com/sponsors/antonmedv

**Comment by nvahalik** [comment]
Done! Happy to sponsor!

... but seriously how can we get this `manifest.json` thing figured out? 😁

**Comment by antonmedv** [comment]
Awesome! I will work on adding those to manifest.

**Comment by antonmedv** [comment]
Fixed!
